name: Uncelestial
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
baseurl: /

defaults:
  -
    scope:
      path: ""
      type: "post"
    value:
      layout: "blog"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "alpha"

permalink: pretty
