name: Uncelestial
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
baseurl: /

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "alpha"

permalink: pretty
